version: '1'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    command: --auth
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data:/data/db
    expose:
      - 27017
  app: 
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGO_URL=mongodb://root:password@mongodb:27017/
    depends_on:
      - mongodb
  messagebus:
    image: rabbitmq:latest
    container_name: messagebus
    hostname: "messagebus"
    labels:
      NAME: "messagebus"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"